const ADD_MESSAGE = "ADD_MESSAGE",
      REMOVE_MESSAGES = "REMOVE_MESSAGES",
      REQUEST_USERS = "REQUEST_USERS",
      RECEIVE_USERS = "RECEIVE_USERS",
      SET_FETCHING_ERROR = "SET_FETCHING_ERROR",
      REMOVE_USERS = "REMOVE_USERS",
      REQUEST_LOGIN_USER = "REQUEST_LOGIN_USER",
      RECEIVE_LOGIN_USER = "RECEIVE_LOGIN_USER",
      REMOVE_LOGIN_USER = "REMOVE_LOGIN_USER"

export {ADD_MESSAGE,
        REMOVE_MESSAGES,
        REMOVE_LOGIN_USER,
        REQUEST_USERS,
        RECEIVE_USERS,
        SET_FETCHING_ERROR,
        REMOVE_USERS,
        REQUEST_LOGIN_USER,
        RECEIVE_LOGIN_USER
};